import math
print(math.sqrt(6))
print(math.ceil(5.9))
print(math.floor(5.6))
print (math.pow(2,5))
print(math.log10(1))
print(math.sin(90))
print(math.degrees(90))
print(math.sinh(90))
print(math.exp(5))
print(math.fabs(10.8))
print(math.factorial(10))